-- MySQL Script generated by MySQL Workbench
-- Wed Nov  5 00:24:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asistencia
-- -----------------------------------------------------
-- Base de datos asistencia

-- -----------------------------------------------------
-- Schema asistencia
--
-- Base de datos asistencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencia` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `asistencia` ;

-- -----------------------------------------------------
-- Table `asistencia`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`programa` (
  `id_programa` INT NOT NULL AUTO_INCREMENT,
  `nombe_programa` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_programa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`semestre` (
  `id_semestre` INT NOT NULL AUTO_INCREMENT,
  `nombre_semestre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(128) NOT NULL,
  `apellidos` VARCHAR(128) NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `email` VARCHAR(64) NULL,
  `genero` VARCHAR(1) NOT NULL,
  `id_programa` INT NOT NULL,
  `id_semestre` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_estudiante_programa_idx` (`id_programa` ASC) VISIBLE,
  INDEX `fk_estudiante_semestre1_idx` (`id_semestre` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_programa`
    FOREIGN KEY (`id_programa`)
    REFERENCES `asistencia`.`programa` (`id_programa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estudiante_semestre1`
    FOREIGN KEY (`id_semestre`)
    REFERENCES `asistencia`.`semestre` (`id_semestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia`.`asistencia` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `observaciones` VARCHAR(255) NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `fk_asistencia_estudiante1_idx` (`id_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_asistencia_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `asistencia`.`estudiante` (`id_estudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
